version: '3'
services:
  waf:
    image: "vshn/modsecurity"
    ports:
    - "8080:80"
    environment:
    - PARANOIA=4
    - PORT=80
    - ANOMALY_INBOUND=100
    - BACKEND=http://10.1.0.102:80
    networks:
      test:
        ipv4_address: 10.1.0.101
  dvwa:
    image: "vulnerables/web-dvwa"
    ports:
    - "81:80"
    networks:
      test:
        ipv4_address: 10.1.0.102

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
